weights: ./yolov5/chest_yaml/yolov5m6.pt
cfg: ./yolov5/chest_yaml/yolov5m6.yaml
data: ./yolov5/chest_yaml/chest_1024_4.yaml
hyp: ./yolov5/data/hyp.scratch.yaml
epochs: 36
batch_size: 12
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
world_size: 1
global_rank: -1
save_dir: runs/train/exp66
total_batch_size: 12
